var _tmr=_tmr||[];
(function(){function u(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function v(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function W(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function X(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function ia(){var a=arguments,b=a[0]||{},c=!1,d=1,k=a.length,l,e,t,g,f;"boolean"===typeof b&&(c=b,b=
a[d++]||{});for(X(b)||(b={});d<k;d++)if(null!=(l=a[d]))for(e in l)t=b[e],g=l[e],b!==g&&(c&&g&&(X(g)||(f="[object Array]"===Object.prototype.toString.call(g)))?(f?(f=!1,t=t&&"[object Array]"===Object.prototype.toString.call(t)?t:[]):t=t&&X(t)?t:{},b[e]=ia(c,t,g)):void 0!==g&&(b[e]=g));return b}function wa(a){var b="";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(k){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}
function q(){return(new Date).getTime()}function r(a,b){var c={data:b,raw:a,url:"https://top-fwz1.mail.ru"+a};if(void 0===b)c.dataSplitter=";",c.open=ab,c.connect=bb,c.startListen=cb,c.stopListen=db,c.open(c),c.connect(c);else{var d;"function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=eb,c.connect=fb,c.startListen=gb,c.stopListen=hb,c.open(c),c.connect(c),d=!0):d=!1;d||ib(c)}}function ib(a){var b=g.createElement("iframe"),c=g.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");
c.appendChild(b);g.body.appendChild(c);try{var d=b.contentWindow.document,k=d.createElement("div"),l;for(l in a.data)if(a.data.hasOwnProperty(l)){var e=a.data[l],t=typeof e;if("string"===t||"number"===t){var f=d.createElement("input");f.setAttribute("type","hidden");f.setAttribute("name",l);f.value=e;k.appendChild(f)}}var h=d.createElement("form");h.setAttribute("action",a.url);h.setAttribute("method",xa);h.setAttribute("enctype",ya);h.appendChild(k);var q=d.createElement("div");q.appendChild(h);
d.body.appendChild(q);var n=function(){try{v(b,"load",n),g.body.removeChild(c)}catch(a){m&&console.warn("[TopMailRu] Error#1.2",a)}};u(b,"load",n);h.submit()}catch(p){m&&console.warn("[TopMailRu] Error#1.3",p)}}function eb(a){a._connection=new f.XMLHttpRequest}function fb(a){a._connection.open(xa,a.url);a._connection.setRequestHeader("Content-Type",ya);a._connection.send(ja(a.data,a.dataSplitter))}function gb(a){u(a._connection,"load",a._onload);u(a._connection,"error",a._onerror)}function hb(a){v(a._connection,
"load",a._onload);v(a._connection,"error",a._onerror)}function ab(a){a._connection=new Image}function bb(a){a._connection.src=a.url+ja(a.data,a.dataSplitter)}function cb(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function db(a){a._connection.onload=null;a._connection.onerror=null}function ja(a,b){var c=b||";",d="",k;for(k in a)if(a.hasOwnProperty(k)){var l=a[k],e=typeof l;if("string"===e||"number"===e)d+=c+escape(k)+"="+escape(l)}return d}function Y(a){return(a=g.cookie.match(RegExp("(?:^|; )"+
a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function I(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var k in c)if((b=c[k])||0===b)a+="; "+k,!0!==b&&(a+="="+b);g.cookie=a}function jb(){var a="tmr"+(""+Math.random()).slice(2);try{return J=f.localStorage||null,J.setItem(a,a),J.removeItem(a),!0}catch(b){return J=
null,m&&console.warn("[TopMailRu] Error#1.4",b),!1}}function kb(){if(!Z)return null;for(var a=x.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var k=1;k<=c;k++)b=a[k]+"."+b;var k=""+q(),l={domain:b,path:"/",expires:3E5};try{I("tmr_tcdhn",k,l);var e=Y("tmr_tcdhn"),l=l||{};l.expires=-1;I("tmr_tcdhn","",l);if(e===k)return b}catch(g){m&&console.warn("[TopMailRu] Error#1.8",g)}}return null}function $(a,b){Z&&I(a,b,za);if(ka)try{J.setItem(a,b)}catch(c){m&&console.warn("[TopMailRu] Error#1.6",
c)}}function la(a){var b;if(!(b=Z?Y(a):null)){var c;if(ka)a:{try{c=J.getItem(a);break a}catch(d){m&&console.warn("[TopMailRu] Error#1.5",d)}c=null}else c=null;b=c}return b}function Aa(a){var b=";e="+escape("detect");r(y(a,"/tracker",!1,!1)+b)}function Ba(a,b){if(a.length&&null!==b.ecom_data){var c=O(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=ma("_m",b.ecom_method),k=ma("_t",b.ecom_type),l=ma("_jst",Ca()),c="{"+c+d+k+l+"}";r(y({id:a[0]},"/datalayer",
!1,!1)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function ma(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function lb(){var a=Y(Da);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=q()-b;return 0>b||b>Ea?null:{id:a[0],version:a[1]}}function h(){}function P(a){a&&"object"===typeof a&&(!B&&"id"in a)&&(B=a.id)}function mb(a){return(a=!C?void 0:C[a])&&na?a-na:void 0}function Fa(){if(C){for(var a=
0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=!C?void 0:C[b[c]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function Q(a){return a&&"object"===typeof a&&("id"in a&&a.id||B)}function y(a,b,c,d){$(oa,++K);var k="id"in a?a.id:B,l="url"in a?a.url:x.href,e="referrer"in a?a.referrer:g.referrer,t="title"in a?a.title:g.title,h;h=pa;null===h&&(h=nb());h=null!==h?h?1:0:null;var p="userid"in a?a.userid:z||
0===z?z:void 0,u=F?F:void 0,n;n=[];B&&k!==B&&n.push("sec");"dataLayer"in f&&n.push("dl");E&&n.push(["ecom"].concat(E).join("-"));qa&&qa.length&&n.push(["jst"].concat(qa).join("-"));n=n.join(",");var s=f.screen,r,w=(new Date).getTimezoneOffset();r="";if(f.Intl)try{r=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(ob){m&&console.warn("[TopMailRu] Error#1.1",ob)}r=w+"/"+r;w=Ga;w=null!==w?w:lb();a.start=Fa();b=b+"?js=13"+(k?";id="+escape(k):"")+(l?";u="+escape(l):"")+(e?";r="+escape(e):"")+
(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==p?";userid="+escape(p):"")+(void 0!==u?";uparams="+escape(O(u)):"")+(d&&t?";title="+encodeURIComponent(t):"")+(s?";s="+s.width+"*"+s.height:"")+";vp=";k=d=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(d=g.documentElement.clientWidth,k=g.documentElement.clientHeight):"number"==typeof f.innerWidth&&
(d=f.innerWidth,k=f.innerHeight);b=b+(""+d+"*"+k)+";touch="+pb+";hds="+qb+";frame="+rb+";flash=";if(null===R)if(R="",D.plugins&&D.plugins["Shockwave Flash"])R=D.plugins["Shockwave Flash"].description.split(" ")[2];else if(f.ActiveXObject)try{var A=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),A=A.GetVariable("$version"),A=A.split(" ")[1].split(",");R=A[0]+"."+A[1]}catch(sb){m&&console.warn("[TopMailRu] Error#1.12",sb)}A=b+R+";sid="+Ha+";ver="+Ia+";tz="+encodeURIComponent(r);if(c){if(!C||!ra)c=
"";else{c=[];c.push(ra.type);c.push(ra.redirectCount);c.push(na);for(b=0;b<Ja.length;b++)c.push(mb(Ja[b]));c=c.join("/")}c=";nt="+c}else c="";c=A+c+("device"in a?";device="+escape(a.device):"")+";ni=";if(!D||!D.connection)A="";else{A=D.connection;b=[];for(k=0;k<Ka.length;k++){d=A[Ka[k]];if(void 0!==d)switch(d){case !0:d=1;break;case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}b.push(d)}A=b.join("/")}return c+A+("params"in a?";params="+escape(O(a.params)):"")+(null!==h?";detect="+h:"")+(Z||ka?
";lvid="+escape([S,q(),K,L].join(":")):"")+(n?";opts="+escape(n):"")+(w?";flocid="+escape(w.id)+";flocv="+escape(w.version):"")+("version"in a?";appver="+escape(a.version):"")+(M.support?";visible="+M.getValue():"")+";_="+Math.random()}function La(a){a=";e="+escape("PVT/"+a);for(var b=0;b<s.length;b++)r(y(s[b],"/tracker",!1,!0)+a)}function tb(){pa=!0;Ma(1);if(!Na&&!T){T=!0;for(var a=0;a<s.length;a++)Aa(s[a])}}function ub(){Ma(0);pa=!1}function nb(){var a=Y(Oa);if(null===a)return null;a=a.split("|");
if(2!==a.length)return null;var b=a[1],b=q()-b;if(0>b||b>Pa)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Ma(a){var b=q();a=[a,b].join("|");I(Oa,a,{path:"/",expires:Pa})}function aa(){g.addEventListener?(v(g,"DOMContentLoaded",aa),_tmr.onready()):g.attachEvent&&"complete"===g.readyState&&(v(g,"readystatechange",aa),_tmr.onready())}function Qa(){v(f,"load",Qa);_tmr.onready();_tmr.onload()}function ba(){v(f,"unload",ba);v(f,"beforeunload",ba);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var f=
window,D=navigator,g=document,x=location,U="string"===typeof x.hostname?x.hostname:"",ca=-1!=U.search(/(^|\.)odnoklassniki\.ru$/)||-1!=U.search(/(^|\.)ok\.ru$/),da=-1!=U.search(/(^|\.)vk\.com$/),vb=-1!=U.search(/(^|\.)lamoda\.ru$/),wb=-1!=U.search(/(^|\.)kommersant\.ru$/),xb="string"===typeof x.search&&-1!=x.search.search(/[?&]rb_clickid=/),m="string"===typeof x.search&&-1!=x.search.search(/[?&]tmr_debug=1(?:&|$)/),Ra=ca||da||vb||wb,yb=!xb,zb=ca||da,Ab=ca||da,Sa=ca||da,Na=!1,O=f.JSON&&JSON.stringify?
JSON.stringify.bind(JSON):function(a){return""},xa="POST",ya="application/x-www-form-urlencoded",Z=!(0===x.hostname.search(/^(\d+.)+\d+$/g)||-1!==x.hostname.search(/:/g)),J=null,ka=jb(),za={domain:kb(),path:"/",expires:287712E5};(function(){var a;if(a=g.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,k=a.length;d<k;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){b=0;for(d=a.length;b<d;b++)k=a[b][0],c=za||{},c.expires=
-1,I(k,"",c)}})();var T=!1,pa=null,Pa=864E5,Oa="tmr_detect",Bb=function(){function a(a,b){for(var c=a.length,e,g,f=0;f<b;f++)g=Math.floor(Math.random()*c),e=a[f],a[f]=a[g],a[g]=e;return a.slice(0,b)}function b(b,k){var l=g.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,
53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,
120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);l.setAttribute("class",e.join(" "));l.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");l.setAttribute("id","trg-b-banners-1");l.setAttribute("data-view","SlotView.mimic");this.bait=g.body.appendChild(l);
this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=k||null;var f=this;setTimeout(function(){f._checkBait.call(f)},1)}var c=7;b.prototype._checkBait=function(){if(T)this._stop();else{var a=!1;null!==g.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||
0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==f.getComputedStyle&&(a=f.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){m&&console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(h){m&&
console.warn("[TopMailRu] Error#1.10",h)}}};b.prototype._stop=function(){try{g.body.removeChild(this.bait)}catch(a){m&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),E=null,Ta="ecommerce",Ua=!1,sa=[],Cb=[36383,2540645,3171181,3074137,2057653],Db=[],Va;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var k={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},e=0,g=b.length;e<g;e++){var f=w[b[e]];if(f){a(k.ecom_method,
[b[e]]);for(var l=0,h=f.length;l<h;l++)for(var t=0,m=d.length;t<m;t++){var p=f[l][d[t]];if(p)for(var n=0,q=c.length;n<q;n++)if(-1!==f[l].type.indexOf(c[n])){a(k.ecom_type,[c[n]]);a(k.ecom_data.events,p);break}}}}return k}function c(a,b,c){if(!a||!c||!(b in w))return null;for(var d,k=0,e=w[b].length;k<e;k++)if(d=w[b][k],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],e,f,n=0,w=a.length;n<w;n++)if(f=a[n]){e=null;try{if(f.ecommerce)e=
k(f)||g(f);else if(null===f.ecommerce)e=null;else if(f.event){var r={event:f.event,ecommerce:{}};e=k(r)||g(r)}else if("event"===f[0]){var x=f[1],y=f[2],z=c(x,p,s);z&&(z.ecom_data[x]=y);e=z}else if(f.event===Ta)a:{for(var v=b([h],[q],[u]),B=0,C=v.ecom_data.events.length;B<C;B++)if(!f.hasOwnProperty(v.ecom_data.events[B])){e=null;break a}delete v.ecom_data.events;v.ecom_data[Ta]=f;e=v}}catch(D){m&&console.warn("[TopMailRu] Error#1.23",D),e=null}e&&(d.push(e),sa.push(e))}if(d.length){a=0;for(e=d.length;a<
e;a++)Ba(ea,d[a]);E||(E=[0,0]);E[0]+=d.length;e=a=0;for(n=d.length;e<n;e++)a+=O(d[e].ecom_data).length;E[1]+=a}}function k(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,h,r))){if(a.event&&(d=c(a.event,h,n)))for(var e=0,k=b.ecom_type.length;e<k;e++)-1===d.ecom_type.indexOf(b.ecom_type[e])&&(b.ecom_type.splice(e,1),k--,e--);b.ecom_data=a.ecommerce;return b}return null}function g(a){var b=a.event,d=c(b,h,n);d&&(d.ecom_data[b]=a.ecommerce);return d}function e(a){if((a=f[a])&&
"function"===typeof a.push){d(a);var b=a.push;a.push=function(){var a=b.apply(this,arguments);d([].slice.call(arguments,0));return a}}}var h="push",p="gtag",q="gse",r="inner",n="outer",s="external",u="required",w={};w[p]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},
{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];w[h]=[{type:[q],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([p],["ga4"],[s]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},
{type:["ym","gee"],inner:["add","detail","purchase","remove"]}];Va=function(){e("dataLayer");Ua=!0}})();var Ca=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]}];return function(){var b;try{b=Object.keys(f).join(",")}catch(c){b=null}for(var d=[],k=0,g=a.length;k<g;k++){var e;a:{e=a[k].globalVars;for(var h=b,m=0,p=e.length;m<p;m++){var q=e[m];if("string"===typeof q&&!(q in f)||"string"===typeof q.re&&
(h&&-1===h.search(RegExp("($|,)"+q.re+"(,|^)","m"))||1===p)){e=!1;break a}}e=!0}e&&d.push(a[k].id)}return d}}(),qa=Ca(),Ea=864E5,Da="tmr_floc",Ga=null;(function(a){try{g.interestCohort&&"function"===typeof g.interestCohort&&g.interestCohort().then(function(a){Ga={id:a.id,version:a.version};a=[a.id,a.version];var b=q();a=a.concat(b).join("|");I(Da,a,{path:"/",expires:Ea})},function(){})}catch(b){}})();var M={support:!1},M=function(){function a(){d(l)}function b(){d(l,r)}function c(){return e?!g[e]:
null}function d(a,b){var d=q(),e="undefined"===typeof b?c():b;if(null===n[a])n[a]={ts:d,state:e,total:0};else{var f=n[a];if(f.state!==e){var g=d-f.ts,h=f.state;f.ts=d;f.state=e;g<k||(h===m?(f.total+=g,s&&s(d,g)):h===p&&v&&v(d,g))}}}var k=5,l="auto",e=null,h=null,m=!0,p=!1,r=null;"hidden"in g?(e="hidden",h="visibilitychange"):"mozHidden"in g?(e="mozHidden",h="mozvisibilitychange"):"webkitHidden"in g?(e="webkitHidden",h="webkitvisibilitychange"):"msHidden"in g&&(e="msHidden",h="msvisibilitychange");
var n={};n[l]=null;var s=n.user=null,v=null;return{support:!!e,auto:function(c,d){s=c||null;v=d||null;e&&(a(),u(g,h,a));u(f,"beforeunload",b);u(f,"unload",b)},set:function(a){d("user",!!a)},getLog:function(){var a=q(),b={},c,d;for(d in n)c=n[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:c}}();M.auto();var Ia="60.3.0",ta=0,fa=0,Ha=wa(16),z=null,F=null,ga=0,oa="tmr_reqNum",K=la(oa),K=null===K?0:parseInt(K,10);$(oa,K);var L=la("tmr_lvid"),S=la("tmr_lvidTS");if(null===L||-1===L.search(/^[0-9a-fA-F]+$/))L=
wa(32);$("tmr_lvid",L);if(null===S||-1===S.search(/^\d+$/))S=""+q();$("tmr_lvidTS",S);var B=0,s=[],ua=[],ha=[],ea=[],pb="ontouchstart"in f||1<(D.maxTouchPoints||D.msMaxTouchPoints)?"1":"0",qb=f.devicePixelRatio||0,rb=f.top===f?0:1,R=null,Wa=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},C=Wa.timing||{},ra=Wa.navigation||{},Ja="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
na=!C?void 0:C.navigationStart,Ka="downlink downlinkMax effectiveType rtt saveData type".split(" "),G,va;G=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||B,f=c.title||null,g,e=va(b,{params:c.required,fn:c.fn});if(e.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<e.missed.length&&e.missed.slice(0,-1).join(", ")+" and "||"")+e.missed.slice(-1)+" in "+a);else{var h=va(b,{params:c.optional,fn:c.fn});g=[].concat(e.values).concat(h.values);e=[].concat(e.missed).concat(h.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?g.push("value: "+b):e.push("value"));c=g.length?"{ "+g.join(", ")+" }":"";g=e.length?"("+(1<e.length?e.slice(0,-1).join(", ")+" and "+e.slice(-1)+" are":e.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(f||a)+" "+c+" "+g):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};va=function(a,b){var c=[],d=[],f,g,e;if(b.params)for(f in b.params)if(b.params.hasOwnProperty(f)&&
!1!==b.params[f])if(g=f in a&&a[f],!0!==b.params[f]&&(g=g||b.params[f]),g)try{e=b.fn?b.fn:null,c.push(f+': "'+(e?e(f,g):g)+'"')}catch(h){console.warn("[TopMailRu] Error#1.16",h)}else d&&d.push(f);return{values:c,missed:d}};h.prototype.callbackOnReady=function(a){m&&G("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&a.callback.call(a.context||null)};h.prototype.pageView=function(a){P(a);if(a&&("object"===typeof a&&a.id)&&(5>ua.length&&!W(a.id,ua)&&(ua.push(a.id),
!1!==a.beat&&ha.push(a.id),s.push(a),T&&Aa(a)),5>ea.length&&!W(a.id,ea)&&(!0===a.ecom||!1!==a.ecom&&(W(a.id,Cb)||!W(a.id,Db))))){ea.push(a.id);var b=[a.id];if(Ua)for(var c=0,d=sa.length;c<d;c++)Ba(b,sa[c])}m&&G("pageView",a,{title:"Page view",optional:{url:x.href}});Q(a)&&(r(y(a,"/counter",!1,!0)),fa=q())};h.prototype.reachGoal=function(a){P(a);m&&G("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(Q(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";r(y(a,
"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};h.prototype.itemView=function(a){m&&G("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(Q(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",f=a.totalvalue||0;(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||B)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+f+"&_="+Math.random();b="IV:"+f+"/"+(""+b).replace(/;/g," ")+";"+
(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");r(y(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.sendEvent=function(a){P(a);m&&G("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(Q(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+
("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");r(y(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?m&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(z=a,m&&console.info("[TopMailRu]: Global user ID = "+z))}};h.prototype.getUserID=function(){return z||0===z?z:void 0};
h.prototype.deleteUserID=function(){z=null;m&&console.info("[TopMailRu]: Reset global user ID to null")};h.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(X(a)){try{F=ia(!0,{},a)}catch(b){m&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}m&&console.info("[TopMailRu]: Global user params = "+O(F))}else m&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};h.prototype.getUserParams=function(){var a=
F?F:void 0;return a?ia(!0,{},a):void 0};h.prototype.deleteUserParams=function(){F=null;m&&console.info("[TopMailRu]: Reset global user params to null")};h.prototype.getClientID=function(){var a=L;return a||0===a?a:void 0};h.prototype._MT_event=function(a,b,c){P(a);m&&G(b,a,{title:c});Q(a)&&r(y(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};h.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};h.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in
a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "miniAppEvent":this.miniAppEvent(a)}}else m&&
console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else m&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};h.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var Xa=!1;h.prototype.onready=function(){Xa||(Xa=!0,!Na&&!T&&Bb(tb,ub),Va())};var Ya=!1;h.prototype.onload=function(){if(!Ya){Ya=!0;ga=q();if(!Ab&&0<s.length){for(var a=";e="+escape("RT/load")+";et="+ga,b=0;b<s.length;b++)r(y(s[b],"/tracker",!0,!1)+a);fa=ga}yb||
setTimeout(function(){La(2)},2E3);zb||setTimeout(function(){La(15)},15E3)}};h.prototype.beat=function(){if(!Ra&&ta){var a=q();if(!(12E4<a-ta)){if(12E4<a-fa)for(var b=";e="+escape("RT/resend")+";et="+ga,c=0;c<s.length;c++)!1!==s[c].beat&&r(y(s[c],"/tracker",!1,!0)+b);else 0<ha.length&&r("/tracker?"+ja({js:"13",id:ha[0],e:"RT/beat",sid:Ha,ids:ha.join(),ver:Ia,_:Math.random()},";"));fa=a}}};var Za=!1;h.prototype.unload=function(){if(!Za&&(Za=!0,!Sa)){var a;a=(a=Fa())?q()-a:void 0;a=";e="+escape("RT/unload")+
";et="+q()+(a?";pvt="+escape(a):"");if(M.support){var b=M.getLog();a+=";vtauto="+b.auto}for(b=0;b<s.length;b++)r(y(s[b],"/tracker",!1,!1)+a)}};h.prototype.activity=function(a){ta=q()};var N=_tmr;_tmr=new h;for(var p=0,V=N.length,H;p<V;p++)(H=N[p])&&"object"===typeof H&&P(H);p=0;for(V=N.length;p<V;p++)H=N[p],_tmr.processEvent(H,1);p=0;for(V=N.length;p<V;p++)H=N[p],_tmr.processEvent(H,-1);if("complete"===g.readyState||"loading"!==g.readyState&&!g.documentElement.doScroll)_tmr.onready();else g.addEventListener?
u(g,"DOMContentLoaded",aa):g.attachEvent&&u(g,"readystatechange",aa);if("complete"===g.readyState)_tmr.onload();else u(f,"load",Qa);Sa||(u(f,"unload",ba),u(f,"beforeunload",ba));if(!Ra){setInterval(function(){_tmr.beat()},6E4);try{for(var $a="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),Eb=function(a){u(g,a,function(){_tmr.activity(a)})},p=0;p<$a.length;p++)Eb($a[p]);u(f,"scroll",function(){_tmr.activity("scallback")})}catch(Fb){m&&console.warn("[TopMailRu] Error#1.20",
Fb)}}}})();
